index: index.md
title: GesturePlay
description: GesturePlay is an open-source machine learning driven gesture recognition software, allowing you to control games with just a camera. Download now to revolutionise your gaming experience!
favicon: "/assets/images/favicon.png"
remote_theme: pages-themes/tactile@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme
github:
  zip_url: https://drive.google.com/uc?export=download&id=1Irpv95kmE1xdyMRLBM_lBM7yxi2RyQae