index: index.md
title: GesturePlay
description: Elevate gaming with AI-powered hand gestures. Immerse yourself in a revolutionized gaming experience!
show_downloads: true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
github:
  zip_url: https://github.com/bgrntgh/FYP-23-S4-30/releases/tag/vX.X.X