index: index.md
title: GesturePlay
description: GesturePlay is an open-source machine learning driven gesture recognition software, allowing you to control games with just a camera. Download now to revolutionise your gaming experience!
remote_theme: pages-themes/tactile@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme
github:
  zip_url: https://github.com/bgrntgh/FYP-23-S4-30/releases/tag/vX.X.X